//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:01:22 AM GMT+03:00 
//


package com.dmitrykolesnikovich.booksIndex.model;

import javax.ejb.Stateful;
import javax.ejb.Stateless;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Model;
import javax.inject.Named;
import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for book complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="book">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isbn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "book", propOrder = {
    "isbn",
    "author",
    "title"
})
@Model
public class Book {

  @XmlElement(required = true)
  protected String isbn;
  @XmlElement(required = true)
  protected String author;
  @XmlElement(required = true)
  protected String title;

  /**
   * Gets the value of the isbn property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getIsbn() {
    return isbn;
  }

  /**
   * Sets the value of the isbn property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setIsbn(String value) {
    this.isbn = value;
  }

  /**
   * Gets the value of the author property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Sets the value of the author property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAuthor(String value) {
    this.author = value;
  }

  /**
   * Gets the value of the title property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTitle() {
    return title;
  }

  /**
   * Sets the value of the title property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTitle(String value) {
    this.title = value;
  }

  @Override
  public String toString() {
    return "Book{" +
        "isbn='" + isbn + '\'' +
        ", author='" + author + '\'' +
        ", title='" + title + '\'' +
        '}';
  }

}
