//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 12:23:47 PM GMT+03:00 
//

// devnote: ^{0,1}[0-9]{1}[-]{1}[0-9]{3}[-]{1}[0-9]{5}[-]{1}[0-9]{0,1}$ matches 1-111-11111-1

package com.dmitrykolesnikovich.booksIndex.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for book complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="book"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isbn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "book", propOrder = {
    "id",
    "isbn",
    "author",
    "title"
}, namespace = "")
@Entity(name = "books")
@NamedQueries({
    @NamedQuery(name = "books.list", query = "SELECT b FROM books b"),
    @NamedQuery(name = "books.findByAuthorOrTitle", query = "SELECT b FROM books b WHERE b.author LIKE :query OR b.title LIKE :query")
})
public class Book {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;

  @Pattern(regexp = "^{0,1}[0-9]{1}[-]{1}[0-9]{3}[-]{1}[0-9]{5}[-]{1}[0-9]{0,1}$")
  @XmlElement(required = true)
  protected String isbn;

  @NotNull
  @Size(min = 1, max = 80)
  @XmlElement(required = true)
  protected String author;

  @NotNull
  @Size(min = 1, max = 80)
  @XmlElement(required = true)
  protected String title;

  /**
   * Gets the value of the isbn property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getIsbn() {
    return isbn;
  }

  /**
   * Sets the value of the isbn property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setIsbn(String value) {
    this.isbn = value;
  }

  /**
   * Gets the value of the author property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Sets the value of the author property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAuthor(String value) {
    this.author = value;
  }

  /**
   * Gets the value of the title property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTitle() {
    return title;
  }

  /**
   * Sets the value of the title property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTitle(String value) {
    this.title = value;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }
}
