//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:01:22 AM GMT+03:00 
//


package com.dmitrykolesnikovich.booksIndex.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.dmitrykolesnikovich.booksIndex.webclient.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Books_QNAME = new QName("", "books");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dmitrykolesnikovich.booksIndex.webclient.model
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Book }
   */
  public Book createBook() {
    return new Book();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Book }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "book")
  public JAXBElement<Book> createBook(Book value) {
    return new JAXBElement<Book>(_Books_QNAME, Book.class, null, value);
  }

  /**
   * Create an instance of {@link BookList }
   */
  public BookList createBookList() {
    return new BookList();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BookList }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "bookList")
  public JAXBElement<BookList> createBookList(BookList value) {
    return new JAXBElement<BookList>(_Books_QNAME, BookList.class, null, value);
  }

}
